controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    skid_control:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

skid_control:
  ros__parameters:

    publish_rate: 30.0 # You can set this higher than the controller manager update rate, but it will be throttled
    base_frame_id: base_link

    left_wheel_names: ['left_back_wheel_joint','left_front_wheel_joint']
    right_wheel_names: ['right_back_wheel_joint','right_front_wheel_joint']
    wheel_separation: 0.3
    wheel_radius: 0.1

    use_stamped_vel: false

    linear:
      x:
        has_velocity_limits    : true
        max_velocity           : 0.2   # m/s
        has_acceleration_limits: true
        max_acceleration       : 2.0   # m/s^2
    angular:
      z:
        has_velocity_limits    : true
        max_velocity           : 4.0   # rad/s
        has_acceleration_limits: true
        max_acceleration       : 25.0   # rad/s^2
    

# joint_broad:
  # ros__parameters: